config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  root 'notes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, :note, :date, :presence => true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    # Faz a busca pelo parâmetro procurado ou mostra todas as anotações do usuário logado
    unless params["Buscar"].blank?
      busca = params["Buscar"]
      @notes = Note.where("title ilike '%#{busca}%' OR note ilike '%#{busca}%'").where(user_id: current_user[:id]).order("notes.title DESC")
    else
      @notes = Note.where(user_id: current_user[:id])
    end
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(
      title: note_params["title"],
      note: note_params["note"],
      date: note_params["date"],
      priority: note_params["priority"],
      user_id: current_user[:id]
    )

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :note, :date, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotações</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Anotações</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li><%= link_to "Nova anotação", new_note_path, class: "nav-link" %></li>
        </ul>
        <form class="form-inline my-2 my-lg-6">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete  %></li>
            <% else %>
              <li><%= link_to "Cadastrar", new_user_registration_path, class: "nav-link" %></li>
              <li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </form>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% elsif alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<body>
  <div class="container">
    <div class="card card-signin my-5">
      <div class="card-body">
        <%= form_with(model: note, local: true) do |form| %>
          <% if note.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

              <ul>
              <% note.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <h5 class="card-title text-center">Nova Anotação</h5>

          <div class="form-group">
            <%= form.label "Título" %>
            <%= form.text_field :title, id: :note_title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label "Anotação" %>
            <%= form.text_area :note, id: :note_note, class: "form-control", rows: "3" %>
          </div>
          <div class="form-group">
            <%= form.label "Data" %>
            <%= form.text_field :date , id: :note_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label "Prioridade" %>
            <%= form.select :priority, options_for_select([["Alta", 1], ["Média", 2], ["Baixa", 3]]), {}, id: :note_priority, class: "form-control" %>
          </div>

          <div class="actions">
            <%= link_to 'Voltar', notes_path, class: "btn btn-primary" %>
            <%= form.submit "Criar", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/notes/edit.html.erb
<body>
  <div class="container">
    <div class="card card-signin my-5">
      <div class="card-body">
        <%= form_with(model: @note, local: true) do |form| %>
          <% if @note.errors.any? %>
              <div id="error_explanation">
              <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

              <ul>
              <% @note.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
              </ul>
              </div>
          <% end %>
          <h5 class="card-title text-center">Editar Anotação</h5>

          <div class="form-group">
              <%= form.label "Título" %>
              <%= form.text_field :title, id: :note_title, class: "form-control" %>
          </div>
          <div class="form-group">
              <%= form.label "Anotação" %>
              <%= form.text_area :note, id: :note_note, class: "form-control", rows: "3" %>
          </div>
          <div class="form-group">
              <%= form.label "Data" %>
              <%= form.text_field :date , id: :note_date, class: "form-control" %>
          </div>
          <div class="form-group">
              <%= form.label "Prioridade" %>
              <%= form.select :priority, options_for_select([["Alta", 1], ["Média", 2], ["Baixa", 3]]), {}, id: :note_priority, class: "form-control" %>
          </div>

          <div class="actions">
              <%= form.submit "Editar", class: "btn btn-primary" %>
              <%= link_to 'Voltar', notes_path, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>
<body>
  <div class="container">
    <div class="card card-signin my-5">
      <div class="card-body">
        <%= form_with(model: @note, local: true, method: 'get', url: root_path) do |form| %>
          <h5 class="card-title text-center">Buscar Anotações</h5>
          <br>
          <fieldset>
            <div class="input-group input-group-btn">
              <%= form.text_field "Buscar", class: "form-control", id: "search", placeholder: "Buscar..."%>
              <%= form.submit "Buscar", class: "btn btn-primary" %>
            </div>
          </fieldset>

          <section>
            <% if @notes.present? %>
              <table class="table">
              <br>
              <thead>
                <tr>
                  <th>Título</th>
                  <th>Nota</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <% @notes.each do |note| %>
                <tbody>
                  <tr>
                    <td><%= note.title.camelize %></td>
                    <td><%= note.note %></td>
                    <td><%= link_to 'Visualizar', note, class: "btn btn-primary" %></td>
                    <td><%= link_to 'Editar', edit_note_path(note), class: "btn btn-primary" %></td>
                    <td><%= link_to 'Deletar', note, method: :delete, class: "btn btn-primary", data: { confirm: "Deletar #{note.title}?" } %></td>
                  </tr>
                </tbody>
              <% end %>
            <% end %>
          </section>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<body>
  <div class="container">
    <div class="card card-signin my-5">
      <div class="card-body">
        <p>
          <strong>Título:</strong>
          <%= @note.title %>
        </p>

        <p>
          <strong>Anotação:</strong>
          <%= @note.note %>
        </p>

        <p>
          <strong>Data:</strong>
          <%= @note.date.strftime("%d/%m/%Y") %>
        </p>

        <p>
          <strong>Prioridade:</strong>
          <% if @note.priority == 1 %>
            <%= "Alta" %>
          <% elsif @note.priority == 2 %>
            <%= "Média" %>
          <% else %>
            <%= "Baixa" %>
          <% end %>
        </p>

        <%= link_to 'Editar', edit_note_path(@note), class: "btn btn-primary" %>
        <%= link_to 'Voltar', notes_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</body>